.PHONY : all
all:
	cd ./DoubleLinkedList && make $@
	cd ./ExampleApplication && make $@
	echo "All built!"

.PHONY : clean
clean:
	cd ./DoubleLinkedList && make $@
	cd ./ExampleApplication && make $@
	echo "All cleaned!"

.PHONY : rebuild
rebuild: clean all